name: mchd_protocol_beta
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  path_provider:
  flutter:
    sdk: flutter 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_plugin_pdf_viewer: any
  numberpicker: ^1.1.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.12.9+5
  fluttertoast: ^3.1.3
  image_picker: ^0.6.1+8
  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  intl: ^0.15.7
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^0.8.4
  photo_view: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/mchd_website-copy.png"
  image_path_ios: "assets/mchd_website-copy.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mchd_website.png
    - assets/mchd_hq_1.png
    - assets/mchd_hq_2.png
    - assets/mchd_logo_big.png
    - assets/mchd_logo_small.png
    - assets/114.png
    - assets/180.png
    - assets/PDFs/adult_guidelines/
    - assets/PDFs/pedi_guidelines/
    - assets/PDFs/adult_guidelines/behavioral/
    - assets/PDFs/adult_guidelines/cardiac/
    - assets/PDFs/adult_guidelines/environmental/
    - assets/PDFs/adult_guidelines/general_medical/
    - assets/PDFs/adult_guidelines/obstetrical/
    - assets/PDFs/adult_guidelines/respiratory/
    - assets/PDFs/adult_guidelines/trauma/
    - assets/PDFs/med_ref_pdf/
    - assets/PDFs/forms_fog_pdf/
    - assets/PDFs/procedures_pdf/
    - assets/PDFs/calendars_2020.pdf
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
